// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_parallel_average
NumericMatrix rcpp_parallel_average(NumericMatrix mat_1);
RcppExport SEXP _fastbioclim_rcpp_parallel_average(SEXP mat_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_1(mat_1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_average(mat_1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastbioclim_rcpp_parallel_average", (DL_FUNC) &_fastbioclim_rcpp_parallel_average, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastbioclim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
