// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_parallel_average
NumericMatrix rcpp_parallel_average(NumericMatrix mat_1);
RcppExport SEXP _fastbioclim_rcpp_parallel_average(SEXP mat_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_1(mat_1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_average(mat_1));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_which_max_rolling_quarter
IntegerMatrix rcpp_parallel_which_max_rolling_quarter(const NumericMatrix& mat, bool wrap, bool na_rm);
RcppExport SEXP _fastbioclim_rcpp_parallel_which_max_rolling_quarter(SEXP matSEXP, SEXP wrapSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_which_max_rolling_quarter(mat, wrap, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_which_min_rolling_quarter
IntegerMatrix rcpp_parallel_which_min_rolling_quarter(const NumericMatrix& mat, bool wrap, bool na_rm);
RcppExport SEXP _fastbioclim_rcpp_parallel_which_min_rolling_quarter(SEXP matSEXP, SEXP wrapSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< bool >::type wrap(wrapSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_which_min_rolling_quarter(mat, wrap, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_which_max_row
NumericMatrix rcpp_parallel_which_max_row(NumericMatrix mat_1);
RcppExport SEXP _fastbioclim_rcpp_parallel_which_max_row(SEXP mat_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_1(mat_1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_which_max_row(mat_1));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_which_min_row
NumericMatrix rcpp_parallel_which_min_row(NumericMatrix mat_1);
RcppExport SEXP _fastbioclim_rcpp_parallel_which_min_row(SEXP mat_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_1(mat_1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_which_min_row(mat_1));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_average_get_quarter
NumericMatrix rcpp_average_get_quarter(NumericMatrix ixQuarter, NumericMatrix mat);
RcppExport SEXP _fastbioclim_rcpp_average_get_quarter(SEXP ixQuarterSEXP, SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type ixQuarter(ixQuarterSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_average_get_quarter(ixQuarter, mat));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_difference
NumericMatrix rcpp_parallel_difference(NumericMatrix mat_1, NumericMatrix mat_2);
RcppExport SEXP _fastbioclim_rcpp_parallel_difference(SEXP mat_1SEXP, SEXP mat_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_1(mat_1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_2(mat_2SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_difference(mat_1, mat_2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_variance
NumericMatrix rcpp_parallel_variance(NumericMatrix mat_1);
RcppExport SEXP _fastbioclim_rcpp_parallel_variance(SEXP mat_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_1(mat_1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_variance(mat_1));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_parallel_sd
NumericMatrix rcpp_parallel_sd(NumericMatrix mat_1);
RcppExport SEXP _fastbioclim_rcpp_parallel_sd(SEXP mat_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_1(mat_1SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_parallel_sd(mat_1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastbioclim_rcpp_parallel_average", (DL_FUNC) &_fastbioclim_rcpp_parallel_average, 1},
    {"_fastbioclim_rcpp_parallel_which_max_rolling_quarter", (DL_FUNC) &_fastbioclim_rcpp_parallel_which_max_rolling_quarter, 3},
    {"_fastbioclim_rcpp_parallel_which_min_rolling_quarter", (DL_FUNC) &_fastbioclim_rcpp_parallel_which_min_rolling_quarter, 3},
    {"_fastbioclim_rcpp_parallel_which_max_row", (DL_FUNC) &_fastbioclim_rcpp_parallel_which_max_row, 1},
    {"_fastbioclim_rcpp_parallel_which_min_row", (DL_FUNC) &_fastbioclim_rcpp_parallel_which_min_row, 1},
    {"_fastbioclim_rcpp_average_get_quarter", (DL_FUNC) &_fastbioclim_rcpp_average_get_quarter, 2},
    {"_fastbioclim_rcpp_parallel_difference", (DL_FUNC) &_fastbioclim_rcpp_parallel_difference, 2},
    {"_fastbioclim_rcpp_parallel_variance", (DL_FUNC) &_fastbioclim_rcpp_parallel_variance, 1},
    {"_fastbioclim_rcpp_parallel_sd", (DL_FUNC) &_fastbioclim_rcpp_parallel_sd, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastbioclim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
