# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_parallel_difference <- function(mat_1, mat_2) {
    .Call(`_fastBioClim_rcpp_parallel_difference`, mat_1, mat_2)
}

matrixMinInd <- function(x) {
    .Call(`_fastBioClim_matrixMinInd`, x)
}

matrixMaxInd <- function(x) {
    .Call(`_fastBioClim_matrixMaxInd`, x)
}

vectorMaxInd <- function(x) {
    .Call(`_fastBioClim_vectorMaxInd`, x)
}

rcpp_which_max_quarter <- function(mat) {
    .Call(`_fastBioClim_rcpp_which_max_quarter`, mat)
}

rcpp_parallel_which_max_quarter <- function(mat_1, mat_2, mat_3) {
    .Call(`_fastBioClim_rcpp_parallel_which_max_quarter`, mat_1, mat_2, mat_3)
}

parallel_random_matrix <- function(n, m, ncores) {
    .Call(`_fastBioClim_parallel_random_matrix`, n, m, ncores)
}

rcpp_get_max_quarter <- function(maxQuarter, mat) {
    .Call(`_fastBioClim_rcpp_get_max_quarter`, maxQuarter, mat)
}

rcpp_parallel_average <- function(mat_1) {
    .Call(`_fastBioClim_rcpp_parallel_average`, mat_1)
}

rcpp_parallel_variance <- function(mat_1) {
    .Call(`_fastBioClim_rcpp_parallel_variance`, mat_1)
}

rcpp_parallel_sd <- function(mat_1) {
    .Call(`_fastBioClim_rcpp_parallel_sd`, mat_1)
}

