# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_parallel_average <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_average`, mat_1)
}

rcpp_parallel_difference <- function(mat_1, mat_2) {
    .Call(`_fastbioclim_rcpp_parallel_difference`, mat_1, mat_2)
}

rcpp_parallel_variance <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_variance`, mat_1)
}

rcpp_parallel_sd <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_sd`, mat_1)
}

