# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_get_average_quarter <- function(ixQuarter, mat) {
    .Call(`_fastbioclim_rcpp_get_average_quarter`, ixQuarter, mat)
}

rcpp_parallel_average <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_average`, mat_1)
}

rcpp_parallel_difference <- function(mat_1, mat_2) {
    .Call(`_fastbioclim_rcpp_parallel_difference`, mat_1, mat_2)
}

rcpp_parallel_which_max_rolling_quarter <- function(mat, wrap = FALSE, na_rm = FALSE) {
    .Call(`_fastbioclim_rcpp_parallel_which_max_rolling_quarter`, mat, wrap, na_rm)
}

rcpp_parallel_which_min_rolling_quarter <- function(mat, wrap = FALSE, na_rm = FALSE) {
    .Call(`_fastbioclim_rcpp_parallel_which_min_rolling_quarter`, mat, wrap, na_rm)
}

rcpp_parallel_which_max_row <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_which_max_row`, mat_1)
}

rcpp_parallel_which_min_row <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_which_min_row`, mat_1)
}

rcpp_parallel_average_quarter <- function(ixQuarter, mat, wrap = FALSE, na_rm = FALSE) {
    .Call(`_fastbioclim_rcpp_parallel_average_quarter`, ixQuarter, mat, wrap, na_rm)
}

rcpp_parallel_variance <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_variance`, mat_1)
}

rcpp_parallel_sd <- function(mat_1) {
    .Call(`_fastbioclim_rcpp_parallel_sd`, mat_1)
}

rcpp_parallel_sum <- function(mat, na_rm = FALSE) {
    .Call(`_fastbioclim_rcpp_parallel_sum`, mat, na_rm)
}

